import Head from 'next/head'
import SearchProfile from '@/searchProfile'

export default function Home() {
  return (
    <div>
      <Head>
        <title>GitHub API </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <SearchProfile/>
    </div>
  )
}
